apiVersion: v1
kind: Service
metadata:
  name: ghost
spec:
  ports:
    - port: 2368
      name: ghost
  selector:
    app: blog-ghost
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: blog-ghost
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: blog-ghost
    spec:
      containers:
      - name: words
        image: sixeyed/fake-blog:ghost-20180305
        imagePullPolicy: Always
        ports:
        - containerPort: 2368
          name: ghost
      imagePullSecrets:
      - name: dockerhubkey